apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-scripts-github-repository
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi